### ISSUE TITLE
Development environment setup steps

### ISSUE THREAD

**Issue by eviltobz** [branan/teensy#2]
I've been following through your tutorial on a fresh Ubuntu installation. By the time that I got to the makefile I thought that I'd build the project, despite the fact that it wouldn't do anything useful, just to check that it was all working. It quickly bailed out with the message: 
```
~/.cargo/bin/xargo build --target=thumbv7em-none-eabi --release
error: couldn't walk the sysroot
caused by: IO error for operation on /home/tobz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src: No such file or directory (os error 2)
caused by: No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` for a backtrace
Makefile:10: recipe for target 'target/thumbv7em-none-eabi/release/teensy' failed
make: *** [target/thumbv7em-none-eabi/release/teensy] Error 1
```

I started poking into the toolchain path it mentions, and got as far as rustlib, but it didn't have a src folder. The tool setup near the top of the page lists:
```
$ rustup component add rust-src
$ rustup toolchain install nightly
$ cargo install xargo
```
seeing the first line mention something about src, I re-ran that line, and then tried make again, at which point it worked fine. Given the paths involved, I'm guessing that the component & toolchain lines just need to be swapped.

**Comment by branan** [comment]
Ah, you're right. Looks like adding the component is per-toolchain. I'll update the post with better language around that
