### ISSUE TITLE
Request: thread::sleep

### ISSUE THREAD

**Issue by paulirotta** [branan/teensy#6]
Have you found an effective way to thread::sleep(Duration::from_millis(4000))
without the standard lib?

**Comment by paulirotta** [comment]
One approach used on an STMDISCOVERY board is at https://github.com/japaric/f3/blob/master/src/delay.rs

We'd need to update that for the timer on teensy, and hopefully find a way to avoid unsafe

**Comment by branan** [comment]
The solution linked has a couple problems to my mind - besides relying on a lot of unsafe, it requires that a specific timer be reserved for the sleep implementation. This can cause all sorts of bad behavior if user code wants to use that timer. It also is implemented as a busy-loop, which I'm not thrilled about.

The implementation in the Teensy Arduino files sets up the systick interrupt to fire every 1ms, and relies on a busy loop polling the number of times it was triggered. This causes your program to be interrupted every ms even if you're not sleeping, and still has the busy-loop on the main thread. I'm not happy with this implementation either.

In my mind, a correct implementation will:
* Allow the user to specify which timer is used for the delay
* Avoid any overhead when not sleeping
* Use the appropriate wait instructions to actually sleep the ARM core when possible.

I've been playing around with using futures.rs to represent DMA transactions. The idea there is that kicking off a DMA transaction sets up an interrupt handler, and returns a future. Calling `.wait()` on that future is just a `wfe` instruction to put the processor to sleep. The DMA interrupt handler will then set the event flag when it is called, and `wfe` will resume execution on interrupt return. I think something similar could be done with timers for a solid sleep function.

The final interface would look something like this:

    let timer = Timer::new();
    let f = timer.sleep_ms(4000);
    f.wait();

Hopefully the code for DMA and futures will be part of post 4. Post 3 is mostly focused on improving the safety of the structs we use to interface with the hardware, and should be done Soon(tm).

**Comment by paulirotta** [comment]
Sounds good. I'll look at a bit more later, but read just today that FreeRTOS was "particularly proud" of a solution similar to what you describe with no ticks when not waiting. So apparently it can be done.

I'm quite pleased so far with the choices you've made, mostly safe code, pin locks etc. Well done! Still a lot to do.

**Comment by paulirotta** [comment]
Deprecated
