### ISSUE TITLE
Where does the flash configuration values come from?

### ISSUE THREAD

**Issue by fogonthedowns** [branan/teensy#7]
I'm reading the [Bootup to LED](https://branan.github.io/teensy/2017/01/12/bootup.html) post and I'm curious where these numbers come from? Could you please document the source code with comments, that show where these values come from?

You mention "Teensy Arduino tooling" but googling this wasn't helpful. 

```
pub static _FLASHCONFIG: [u8; 16] = [
    0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF,
    0xFF, 0xFF, 0xFF, 0xFF, 0xDE, 0xF9, 0xFF, 0xFF
];```

https://github.com/branan/teensy/blob/master/src/main.rs#L108

**Comment by branan** [comment]
Those bytes are from https://github.com/PaulStoffregen/cores/blob/fc79132670ac83ce7cae8e2bac64be109fbfe35e/teensy3/mk20dx128.c#L654-L658

I'm working on a revamped version of this that uses modern Rust toolchains (no more xargo, and the new LLVM-based ARM linker). I'll try to expand the description of what's happening there.

**Comment by branan** [comment]
I've added the link above to Post 1. I'm going to keep this open until I have time to expand upon what the `FSEC` and `FOPT` fields are actually doing

**Comment by branan** [comment]
Looks like I had time sooner than expected. I've updated the post once more with a bit more comment on FSEC and FOPT. I don't want to get too in-depth with what's going on here, since it's pretty tangential to what post 1 is trying to do. Flash security is generally an "advanced" topic
